language : node_js
node_js : 
  - "7.9.0"
script : 
  - npm install
  - npm uninstall firebase angularfire2 --save
  - npm install firebase angularfire2 --save
  - ng build
install : 
  - npm install -g @angular/cli
  - npm install -g firebase-tools

after_success : 
  -firebase deploy --token $FIREBASE_TOKEN  