language : node_js
node_js : 
  - "7.9.0"
script : 
  - npm install
  # - npm i angularfire2@next --save
  - npm install promise-polyfill --save-exact
  - ng build -aot=false
install : 
  - npm install -g @angular/cli
  - npm install -g firebase-tools


after_success : 
  -firebase deploy --token $FIREBASE_TOKEN  